### ISSUE TITLE
Differences to JRebel and DCEVM+Hotswap Agent?

### ISSUE THREAD

**Issue by lathspell** [fakereplace/fakereplace#13]
Could you add a few words to the README.md where you describe the differences between Fakereplace and Hotswap Agent? The latter two are both alternatives to the well known JRebel that are started as JVM Agent. Hotswap Agent does need a patched JVM though (DCEVM) whereas Fakereplace seems not to. Does this mean that Fakereplace has limitations regarding to the other alternatives? Being able to use the stock JVM would certainly be nice.

**Comment by AndrejGajdos** [comment]
I will try to compare JRebel with FakeReplace and DCEVM+Hotswap Agent. I am not sure about all DCEVM and FakeReplace features, so let me know if I am wrong.

**Functionality:**

With FastSwap and DCEVM you cannot modify configuration files, enum values, create or remove classes.

FastSwap doesn't work with annotations, interfaces.
DCEVM doesn't work with static fields, injected fields.

DCEVM+Hotswap Agent and FakeReplace have integration with just a few frameworks. JRebel supports more than 100 frameworks.

**Environments:**

With DCEVM and FastSwap you cannot use remote environment (projects have to be deployed locally).

DCEVM works with only Java version 7 and 8 and you have to replace your JVM, so it perhaps doesn't work with Webspere or Weblogic aplication servers.

It looks like FastSwap works with only maven projects.

**Comment by stuartwdouglas** [comment]
Andrej is pretty much correct. I have not had much time to work on Fakereplace for a number of years now, so it has been very neglected. I may have time to start working on it again in the future but it will depend on my workload.

In terms of integration Fakereplace mostly just integrates with frameworks that form part of Wildfly/JBoss EAP7.

JRebel is maintained by a reasonably sized full time team and has been under active development for years, Fakereplace is something I hacked up in my spare time because I was interested to see if it was possible.
